name: edge-prov

services:
  api:
    image: reserve-api:0.1.0
    expose:
      - "3001"
    environment:
      - TZ=Asia/Tokyo
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:3001/health"]
      interval: 10s
      timeout: 3s
      start_period: 30s
      retries: 3
    networks:
      - edge_net

  web:
    image: reservation-web:0.1.0
    expose:
      - "3002"
    environment:
      - TZ=Asia/Tokyo
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:3002/"]
      interval: 10s
      timeout: 3s
      start_period: 30s
      retries: 3
    depends_on:
      api:
        condition: service_healthy
    networks:
      - edge_net

  nginx:
    image: edge-nginx:0.1.0
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Tokyo
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/", "-o", "/dev/null"]
      interval: 10s
      timeout: 3s
      start_period: 5s
      retries: 3
    depends_on:
      web:
        condition: service_healthy
      api:
        condition: service_healthy
    networks:
      - edge_net

networks:
  edge_net:
    driver: bridge
